/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 *
 * MediaTek Inc. (C) 2016. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek Software")
 * have been modified by MediaTek Inc. All revisions are subject to any receiver's
 * applicable license agreements with MediaTek Inc.
 */
#ifndef __RFX_IMS_MESSAGE_ID_HEADER__
#define __RFX_IMS_MESSAGE_ID_HEADER__

// Request msg id
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_VOLTE_ENABLE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_WFC_ENABLE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_VILTE_ENABLE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_VIWIFI_ENABLE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_IMSCFG)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_MD_IMSCFG)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_GET_PROVISION_VALUE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_PROVISION_VALUE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_WFC_PROFILE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_CONFERENCE_DIAL)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_DIAL_WITH_SIP_URI)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_VT_DIAL_WITH_SIP_URI)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_HOLD_CALL)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_RESUME_CALL)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_ADD_IMS_CONFERENCE_CALL_MEMBER)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_REMOVE_IMS_CONFERENCE_CALL_MEMBER)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_PULL_CALL)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_VIDEO_CALL_ACCEPT)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_IMS_ECT)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_IMS_REGISTRATION_STATE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_IMS_ENABLE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_IMS_DEREG_NOTIFICATION)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_IMS_REGISTRATION_REPORT)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_IMS_RTP_REPORT)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_IMS_VT_DIAL)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_IMS_DIAL)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_IMS_EMERGENCY_DIAL)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_SRVCC_CALL_CONTEXT_TRANSFER)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_VOICE_DOMAIN_PREFERENCE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_GET_IMS_DATA_CALL_INFO)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_REUSE_IMS_DATA_CALL)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_ASYNC_HOLD_CALL)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_ASYNC_RESUME_CALL)

// URC msg id
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_GET_PROVISION_DONE)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_ECONF_SRVCC_INDICATION)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_SIP_CALL_PROGRESS_INDICATOR)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_ECONF_RESULT_INDICATION)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_CALLMOD_CHANGE_INDICATOR)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_VIDEO_CAPABILITY_INDICATOR)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_SRVCC_STATE_NOTIFY)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_ECT_INDICATION)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_IMS_DISABLE_START)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_IMS_ENABLE_START)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_IMS_DISABLE_DONE)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_IMS_ENABLE_DONE)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_IMS_REGISTRATION_INFO)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_RESPONSE_IMS_NETWORK_STATE_CHANGED)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_IMS_DEREG_DONE)
RFX_MSG_ID_EXPN(RFX_MSG_URC_IMS_EVENT_PACKAGE_INDICATION)
RFX_MSG_ID_EXPN(RIL_MSG_UNSOL_VOLTE_SETTING)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_IMS_SUPPORT_ECC)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_IMS_RTP_INFO)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_VT_RING_INFO)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_IMS_MULTIIMS_COUNT)
RFX_MSG_ID_EXPN(RFX_MSG_UNSOL_IMS_ASYNC_CALL_CONTROL_RESULT)

//Event msg id
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_URC_HANDLER_REGISTER_DONE)
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_IMS_REQUEST_HANDLER_REGISTER_DONE)

#endif
