/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 *
 * MediaTek Inc. (C) 2016. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek Software")
 * have been modified by MediaTek Inc. All revisions are subject to any receiver's
 * applicable license agreements with MediaTek Inc.
 */

#ifndef __RFX_NW_MESSAGE_ID_HEADER__
#define __RFX_NW_MESSAGE_ID_HEADER__
// Request msg id
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SIGNAL_STRENGTH)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_VOICE_REGISTRATION_STATE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_DATA_REGISTRATION_STATE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_OPERATOR)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_QUERY_NETWORK_SELECTION_MODE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_NETWORK_SELECTION_AUTOMATIC)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_NETWORK_SELECTION_MANUAL)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_NETWORK_SELECTION_MANUAL_WITH_ACT)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_QUERY_AVAILABLE_NETWORKS)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_QUERY_AVAILABLE_NETWORKS_WITH_ACT)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_ABORT_QUERY_AVAILABLE_NETWORKS)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_BAND_MODE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_QUERY_AVAILABLE_BAND_MODE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_PREFERRED_NETWORK_TYPE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_GET_PREFERRED_NETWORK_TYPE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_GET_NEIGHBORING_CELL_IDS)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_LOCATION_UPDATES)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_VOICE_RADIO_TECH)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_GET_CELL_INFO_LIST)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_UNSOL_CELL_INFO_LIST_RATE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_GET_POL_CAPABILITY)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_GET_POL_LIST)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_POL_ENTRY)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_GET_FEMTOCELL_LIST)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_ABORT_FEMTOCELL_LIST)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SELECT_FEMTOCELL)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_CDMA_SET_ROAMING_PREFERENCE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_CDMA_QUERY_ROAMING_PREFERENCE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SCREEN_STATE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_UNSOLICITED_RESPONSE_FILTER)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_QUERY_FEMTOCELL_SYSTEM_SELECTION_MODE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_FEMTOCELL_SYSTEM_SELECTION_MODE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_VSS_ANTENNA_CONF)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_VSS_ANTENNA_INFO)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_SERVICE_STATE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_PSEUDO_CELL_MODE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_GET_PSEUDO_CELL_INFO)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_GET_GMSS_RAT_MODE)
RFX_MSG_ID_EXPN(RFX_MSG_RIL_REQUEST_START_NETWORK_SCAN)
RFX_MSG_ID_EXPN(RFX_MSG_RIL_REQUEST_STOP_NETWORK_SCAN)
// M: [Network][C2K] For Sprint Roaming Bar @{
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_SET_ROAMING_ENABLE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_GET_ROAMING_ENABLE)
// @}

// URC msg id
RFX_MSG_ID_EXPN(RFX_MSG_URC_RESPONSE_VOICE_NETWORK_STATE_CHANGED)
RFX_MSG_ID_EXPN(RFX_MSG_URC_NITZ_TIME_RECEIVED)
RFX_MSG_ID_EXPN(RFX_MSG_URC_SIGNAL_STRENGTH)
RFX_MSG_ID_EXPN(RFX_MSG_URC_RESPONSE_PS_NETWORK_STATE_CHANGED)
RFX_MSG_ID_EXPN(RFX_MSG_URC_RESPONSE_CS_NETWORK_STATE_CHANGED)
RFX_MSG_ID_EXPN(RFX_MSG_URC_RESTRICTED_STATE_CHANGED)
RFX_MSG_ID_EXPN(RFX_MSG_URC_CDMA_OTA_PROVISION_STATUS)
RFX_MSG_ID_EXPN(RFX_MSG_URC_CDMA_PRL_CHANGED)
RFX_MSG_ID_EXPN(RFX_MSG_URC_VOICE_RADIO_TECH_CHANGED)
RFX_MSG_ID_EXPN(RFX_MSG_URC_CELL_INFO_LIST)
RFX_MSG_ID_EXPN(RFX_MSG_URC_NEIGHBORING_CELL_INFO)
RFX_MSG_ID_EXPN(RFX_MSG_URC_NETWORK_INFO)
RFX_MSG_ID_EXPN(RFX_MSG_URC_RESPONSE_MMRR_STATUS_CHANGED)
RFX_MSG_ID_EXPN(RFX_MSG_URC_FEMTOCELL_INFO)
RFX_MSG_ID_EXPN(RFX_MSG_URC_GMSS_RAT_CHANGED)
RFX_MSG_ID_EXPN(RFX_MSG_URC_NETWORK_EVENT)
RFX_MSG_ID_EXPN(RFX_MSG_URC_RESPONSE_ACMT)
RFX_MSG_ID_EXPN(RFX_MSG_URC_MODULATION_INFO)
RFX_MSG_ID_EXPN(RFX_MSG_URC_RESPONSE_CELLULAR_DATA_REG_STATE)
RFX_MSG_ID_EXPN(RFX_MSG_URC_PSEUDO_CELL_INFO)
RFX_MSG_ID_EXPN(RFX_MSG_URC_NETWORK_SCAN_RESULT)
// Event id
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_CONFIRM_RAT_BEGIN)
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_FEMTOCELL_UPDATE)
RFX_MSG_ID_EXPN(RFX_MSG_EVENT_PS_NETWORK_STATE)
#endif
